application: zen-gae-restx
version: 4
runtime: java
api_version: 1
threadsafe: true

default_expiration: "30d"

handlers:

# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html
  expiration: "5m"

# re-direct to index.html
- url: /index.html(.*)
  static_files: index.html
  upload: index.html(.*)
  expiration: "5m"

# access the static resources in the root director

- url: /components/(.*)
  static_files: components/\1
  upload: (.*)

# access the static resources in the root director

- url: /css/(.*)
  static_files: css/\1
  upload: css/(.*)
  expiration: "5m"

# access the static resources in the root director

- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)
  expiration: "5m"

# access the static resources in the root director

- url: /js/(.*)
  static_files: js/\1
  upload: js/(.*)
  expiration: "5m"

- url: /view/(.*)
  static_files: view/\1
  upload: view/(.*)
  expiration: "5m"

# api

- url: /api/@/*
  login: admin
  servlet: restx.servlet.RestxMainRouterServlet
  name: adminRouter

- url: /api/*
  servlet: restx.servlet.RestxMainRouterServlet
  name: mainRouter

